version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  producer:
    build: ./producer
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - redis
    volumes:
      - ./consumer/logs:/app/logs